
package View;

import Controller.Ctrl_Msg;
import Model.Model_Banco;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class View_Menu extends javax.swing.JFrame {
   
    public View_Menu() {
        this.setExtendedState(MAXIMIZED_BOTH);
        //Model_Banco.Open();
        double largura = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double altura = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        //JOptionPane.showMessageDialog(null, "Altura: " + altura + "\nLargura: " + largura);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mbMenu = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mniCadEstacionamento = new javax.swing.JMenuItem();
        mniCadFuncionario = new javax.swing.JMenuItem();
        mniCadTipoVaga = new javax.swing.JMenuItem();
        mniCadVaga = new javax.swing.JMenuItem();
        mniCadCliente = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mniConVaga = new javax.swing.JMenuItem();
        mniConTipoVaga = new javax.swing.JMenuItem();
        mniConFuncionario = new javax.swing.JMenuItem();
        mniConCliente = new javax.swing.JMenuItem();
        mnControle = new javax.swing.JMenu();
        mniVenda = new javax.swing.JMenuItem();
        mniFinalizacao = new javax.swing.JMenuItem();
        mniCancelamento = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();
        mniSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu EasyPark");

        mnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Easycad.png"))); // NOI18N
        mnCadastros.setMnemonic('c');
        mnCadastros.setText("Cadastros");

        mniCadEstacionamento.setMnemonic('e');
        mniCadEstacionamento.setText("Estacionamento");
        mniCadEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadEstacionamentoActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadEstacionamento);

        mniCadFuncionario.setMnemonic('f');
        mniCadFuncionario.setText("Funcionário");
        mniCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadFuncionarioActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadFuncionario);

        mniCadTipoVaga.setMnemonic('t');
        mniCadTipoVaga.setText("Tipo Vaga");
        mniCadTipoVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadTipoVagaActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadTipoVaga);

        mniCadVaga.setMnemonic('v');
        mniCadVaga.setText("Vaga");
        mniCadVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadVagaActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadVaga);

        mniCadCliente.setMnemonic('c');
        mniCadCliente.setText("Cliente");
        mniCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadClienteActionPerformed(evt);
            }
        });
        mnCadastros.add(mniCadCliente);

        mbMenu.add(mnCadastros);

        mnConsultas.setMnemonic('o');
        mnConsultas.setText("Consultas");

        mniConVaga.setMnemonic('v');
        mniConVaga.setText("Vagas");
        mniConVaga.setToolTipText("");
        mniConVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConVagaActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConVaga);

        mniConTipoVaga.setMnemonic('t');
        mniConTipoVaga.setText("Tipo de Vagas");
        mniConTipoVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConTipoVagaActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConTipoVaga);

        mniConFuncionario.setMnemonic('f');
        mniConFuncionario.setText("Funcionários");
        mniConFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConFuncionarioActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConFuncionario);

        mniConCliente.setMnemonic('c');
        mniConCliente.setText("Clientes");
        mniConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConClienteActionPerformed(evt);
            }
        });
        mnConsultas.add(mniConCliente);

        mbMenu.add(mnConsultas);

        mnControle.setMnemonic('n');
        mnControle.setText("Controle");

        mniVenda.setMnemonic('v');
        mniVenda.setText("Venda");
        mnControle.add(mniVenda);

        mniFinalizacao.setMnemonic('f');
        mniFinalizacao.setText("Finalização");
        mniFinalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFinalizacaoActionPerformed(evt);
            }
        });
        mnControle.add(mniFinalizacao);

        mniCancelamento.setMnemonic('c');
        mniCancelamento.setText("Cancelamento");
        mnControle.add(mniCancelamento);

        mbMenu.add(mnControle);

        mnRelatorios.setMnemonic('r');
        mnRelatorios.setText("Relatórios");
        mbMenu.add(mnRelatorios);

        mnSair.setMnemonic('s');
        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnSair.add(mniSair);

        mbMenu.add(mnSair);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadEstacionamentoActionPerformed
        /*View_CadEstabelecimento frmCadEstabelecimento = new View_CadEstabelecimento();
        frmCadEstabelecimento.setVisible(true);*/
        
    }//GEN-LAST:event_mniCadEstacionamentoActionPerformed

    private void mniCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadFuncionarioActionPerformed
        View_CadFuncionario frmCadFuncionario = new View_CadFuncionario();
        frmCadFuncionario.setVisible(true);
    }//GEN-LAST:event_mniCadFuncionarioActionPerformed

    private void mniCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadClienteActionPerformed
        View_CadCliente frmCadCliente = new View_CadCliente();
        frmCadCliente.setVisible(true);
    }//GEN-LAST:event_mniCadClienteActionPerformed

    private void mniCadTipoVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadTipoVagaActionPerformed
        View_CadTipoVaga frmCadTipoVaga = new View_CadTipoVaga();
        frmCadTipoVaga.setVisible(true);
    }//GEN-LAST:event_mniCadTipoVagaActionPerformed

    private void mniCadVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadVagaActionPerformed
        View_CadVaga frmCadVaga = new View_CadVaga();
        frmCadVaga.setVisible(true);
    }//GEN-LAST:event_mniCadVagaActionPerformed

    private void mniConVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConVagaActionPerformed
        View_ConVaga frmConVaga = new View_ConVaga();
        frmConVaga.setVisible(true);
    }//GEN-LAST:event_mniConVagaActionPerformed

    private void mniConTipoVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConTipoVagaActionPerformed
        View_ConTipoVaga frmConTipoVaga = new View_ConTipoVaga();
        frmConTipoVaga.setVisible(true);
    }//GEN-LAST:event_mniConTipoVagaActionPerformed

    private void mniConFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConFuncionarioActionPerformed
        View_ConFuncionarios frmConFuncionarios = new View_ConFuncionarios();
        frmConFuncionarios.setVisible(true);
    }//GEN-LAST:event_mniConFuncionarioActionPerformed

    private void mniConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConClienteActionPerformed
        View_ConCliente frmConCliente = new View_ConCliente();
        frmConCliente.setVisible(true);
    }//GEN-LAST:event_mniConClienteActionPerformed

    private void mniFinalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFinalizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniFinalizacaoActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        
    }//GEN-LAST:event_mnSairActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
      boolean r =  Ctrl_Msg.Questiona(Ctrl_Msg.MsgQFecharS);
        if (r==true) 
        {
          this.dispose();
        }
    }//GEN-LAST:event_mniSairActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnControle;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem mniCadCliente;
    private javax.swing.JMenuItem mniCadEstacionamento;
    private javax.swing.JMenuItem mniCadFuncionario;
    private javax.swing.JMenuItem mniCadTipoVaga;
    private javax.swing.JMenuItem mniCadVaga;
    private javax.swing.JMenuItem mniCancelamento;
    private javax.swing.JMenuItem mniConCliente;
    private javax.swing.JMenuItem mniConFuncionario;
    private javax.swing.JMenuItem mniConTipoVaga;
    private javax.swing.JMenuItem mniConVaga;
    private javax.swing.JMenuItem mniFinalizacao;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniVenda;
    // End of variables declaration//GEN-END:variables
}
